typedef unsigned long long u64;
u64 right_add_small(u64 u,u64 v,int n,int m) { return (u+v)+(n+1); }
u64 left_add_small(u64 u,u64 v,int n,int m) { return (n+1)+(u+v); }
u64 right_add_large(u64 u,u64 v,int n,int m) { return (u+v)+(n+70000); }
u64 left_add_large(u64 u,u64 v,int n,int m) { return (n+70000)+(u+v); }
u64 right_sub_small(u64 u,u64 v,int n,int m) { return (u+v)+(n-1); }
u64 left_sub_small(u64 u,u64 v,int n,int m) { return (n-1)+(u+v); }
u64 right_sub_large(u64 u,u64 v,int n,int m) { return (u+v)+(n-70000); }
u64 left_sub_large(u64 u,u64 v,int n,int m) { return (n-70000)+(u+v); }
u64 right_add_word(u64 u,u64 v,int n,int m) { return (u+v)+(n+m); }
u64 left_add_word(u64 u,u64 v,int n,int m) { return (n+m)+(u+v); }
u64 right_sub_word(u64 u,u64 v,int n,int m) { return (u+v)+(n-m); }
u64 left_sub_word(u64 u,u64 v,int n,int m) { return (n-m)+(u+v); }
u64 right_mul_small(u64 u,u64 v,int n,int m) { return (u+v)+(n*2); }
u64 left_mul_small(u64 u,u64 v,int n,int m) { return (n*2)+(u+v); }
u64 right_mul_odd(u64 u,u64 v,int n,int m) { return (u+v)+(n*3); }
u64 left_mul_odd(u64 u,u64 v,int n,int m) { return (n*3)+(u+v); }
u64 right_mul_word(u64 u,u64 v,int n,int m) { return (u+v)+(n*m); }
u64 left_mul_word(u64 u,u64 v,int n,int m) { return (n*m)+(u+v); }
u64 right_div_small(u64 u,u64 v,int n,int m) { return (u+v)+(n/3); }
u64 left_div_small(u64 u,u64 v,int n,int m) { return (n/3)+(u+v); }
u64 right_mod_small(u64 u,u64 v,int n,int m) { return (u+v)+(n%3); }
u64 left_mod_small(u64 u,u64 v,int n,int m) { return (n%3)+(u+v); }
u64 right_and_word(u64 u,u64 v,int n,int m) { return (u+v)+(n&m); }
u64 left_and_word(u64 u,u64 v,int n,int m) { return (n&m)+(u+v); }
u64 right_or_word(u64 u,u64 v,int n,int m) { return (u+v)+(n|m); }
u64 left_or_word(u64 u,u64 v,int n,int m) { return (n|m)+(u+v); }
u64 right_xor_word(u64 u,u64 v,int n,int m) { return (u+v)+(n^m); }
u64 left_xor_word(u64 u,u64 v,int n,int m) { return (n^m)+(u+v); }
u64 right_xor_small(u64 u,u64 v,int n,int m) { return (u+v)+(n^1); }
u64 left_xor_small(u64 u,u64 v,int n,int m) { return (n^1)+(u+v); }
u64 right_or_small(u64 u,u64 v,int n,int m) { return (u+v)+(n|1); }
u64 left_or_small(u64 u,u64 v,int n,int m) { return (n|1)+(u+v); }
u64 right_and_negative(u64 u,u64 v,int n,int m) { return (u+v)+(n&-2); }
u64 left_and_negative(u64 u,u64 v,int n,int m) { return (n&-2)+(u+v); }
u64 right_shift_left(u64 u,u64 v,int n,int m) { return (u+v)+(n<<1); }
u64 left_shift_left(u64 u,u64 v,int n,int m) { return (n<<1)+(u+v); }
u64 right_shift_right(u64 u,u64 v,int n,int m) { return (u+v)+(n>>1); }
u64 left_shift_right(u64 u,u64 v,int n,int m) { return (n>>1)+(u+v); }
u64 right_shift_variable(u64 u,u64 v,int n,int m) { return (u+v)+(n>>(m&7)); }
u64 left_shift_variable(u64 u,u64 v,int n,int m) { return (n>>(m&7))+(u+v); }
u64 right_negate(u64 u,u64 v,int n,int m) { return (u+v)+(-n); }
u64 left_negate(u64 u,u64 v,int n,int m) { return (-n)+(u+v); }
u64 right_complement(u64 u,u64 v,int n,int m) { return (u+v)+(~n); }
u64 left_complement(u64 u,u64 v,int n,int m) { return (~n)+(u+v); }
u64 right_nested_add(u64 u,u64 v,int n,int m) { return (u+v)+((n+1)+m); }
u64 left_nested_add(u64 u,u64 v,int n,int m) { return ((n+1)+m)+(u+v); }
u64 right_nested_mul_add(u64 u,u64 v,int n,int m) { return (u+v)+(n*2+1); }
u64 left_nested_mul_add(u64 u,u64 v,int n,int m) { return (n*2+1)+(u+v); }
u64 right_nested_add_mul(u64 u,u64 v,int n,int m) { return (u+v)+((n+1)*2); }
u64 left_nested_add_mul(u64 u,u64 v,int n,int m) { return ((n+1)*2)+(u+v); }
u64 right_mul_one(u64 u,u64 v,int n,int m) { return (u+v)+(n*1); }
u64 left_mul_one(u64 u,u64 v,int n,int m) { return (n*1)+(u+v); }
u64 right_mul_neg_one(u64 u,u64 v,int n,int m) { return (u+v)+(n*-1); }
u64 left_mul_neg_one(u64 u,u64 v,int n,int m) { return (n*-1)+(u+v); }
u64 right_mul_four(u64 u,u64 v,int n,int m) { return (u+v)+(n*4); }
u64 left_mul_four(u64 u,u64 v,int n,int m) { return (n*4)+(u+v); }
u64 right_div_one(u64 u,u64 v,int n,int m) { return (u+v)+(n/1); }
u64 left_div_one(u64 u,u64 v,int n,int m) { return (n/1)+(u+v); }
u64 right_div_neg_one(u64 u,u64 v,int n,int m) { return (u+v)+(n/-1); }
u64 left_div_neg_one(u64 u,u64 v,int n,int m) { return (n/-1)+(u+v); }
u64 right_nested_constants(u64 u,u64 v,int n,int m) { return (u+v)+((n+1)+2); }
u64 left_nested_constants(u64 u,u64 v,int n,int m) { return ((n+1)+2)+(u+v); }
u64 right_nested_shift_add(u64 u,u64 v,int n,int m) { return (u+v)+((n<<1)+1); }
u64 left_nested_shift_add(u64 u,u64 v,int n,int m) { return ((n<<1)+1)+(u+v); }
u64 right_constant_left_sub(u64 u,u64 v,int n,int m) { return (u+v)+(1-n); }
u64 left_constant_left_sub(u64 u,u64 v,int n,int m) { return (1-n)+(u+v); }
u64 right_shift_constant_left(u64 u,u64 v,int n,int m) { return (u+v)+(-1<<(m&7)); }
u64 left_shift_constant_left(u64 u,u64 v,int n,int m) { return (-1<<(m&7))+(u+v); }
u64 right_div_word(u64 u,u64 v,int n,int m) { return (u+v)+(n/(m|1)); }
u64 left_div_word(u64 u,u64 v,int n,int m) { return (n/(m|1))+(u+v); }
u64 right_mod_word(u64 u,u64 v,int n,int m) { return (u+v)+(n%(m|1)); }
u64 left_mod_word(u64 u,u64 v,int n,int m) { return (n%(m|1))+(u+v); }
u64 right_named_mul_word(u64 u,u64 v,int n,int m) { int t=n*m; return (u+v)+(t); }
u64 left_named_mul_word(u64 u,u64 v,int n,int m) { int t=n*m; return (t)+(u+v); }
u64 right_named_div_word(u64 u,u64 v,int n,int m) { int t=n/(m|1); return (u+v)+(t); }
u64 left_named_div_word(u64 u,u64 v,int n,int m) { int t=n/(m|1); return (t)+(u+v); }
