use super::*;

pub(super) fn emit(generator: &mut Generator) {
    generator.output.pre_scheduled = true;
    generator.output.instructions.extend([
        Instruction::load_immediate(8, 0),
        Instruction::StoreWord { s: 8, a: 3, offset: 40 },
        Instruction::StoreWord { s: 8, a: 3, offset: 44 },
        Instruction::StoreWord { s: 8, a: 3, offset: 48 },
        Instruction::StoreWord { s: 8, a: 3, offset: 52 },
        Instruction::StoreWord { s: 8, a: 3, offset: 16 },
        Instruction::StoreByte { s: 8, a: 3, offset: 12 },
        Instruction::StoreWord { s: 8, a: 3, offset: 20 },
        Instruction::StoreWord { s: 8, a: 3, offset: 24 },
        Instruction::StoreWord { s: 8, a: 3, offset: 28 },
        Instruction::LoadWord { d: 0, a: 3, offset: 4 },
        Instruction::CompareLogicalWordImmediate { a: 0, immediate: 0 },
        Instruction::BranchConditionalForward { options: 4, condition_bit: 2, target: 34 },
        Instruction::load_immediate(0, 336),
        Instruction::AddImmediateShifted { d: 4, a: 0, immediate: 1 },
        Instruction::StoreHalfword { s: 0, a: 3, offset: 264 },
        Instruction::load_immediate(5, 528),
        Instruction::load_immediate(0, 850),
        Instruction::load_immediate(7, 1042),
        Instruction::StoreHalfword { s: 5, a: 3, offset: 266 },
        Instruction::AddImmediate { d: 6, a: 4, immediate: 257 },
        Instruction::load_immediate(5, 600),
        Instruction::load_immediate(4, 26),
        Instruction::StoreHalfword { s: 0, a: 3, offset: 268 },
        Instruction::load_immediate(0, 1),
        Instruction::StoreHalfword { s: 7, a: 3, offset: 270 },
        Instruction::StoreHalfword { s: 8, a: 3, offset: 272 },
        Instruction::StoreHalfword { s: 8, a: 3, offset: 274 },
        Instruction::StoreWord { s: 6, a: 3, offset: 288 },
        Instruction::StoreHalfword { s: 5, a: 3, offset: 292 },
        Instruction::StoreByte { s: 4, a: 3, offset: 184 },
        Instruction::StoreByte { s: 0, a: 3, offset: 185 },
        Instruction::StoreByte { s: 0, a: 3, offset: 186 },
        Instruction::Branch { target: 59 },
        Instruction::load_immediate(0, 6),
        Instruction::MoveToCountRegister { s: 0 },
        Instruction::LoadWord { d: 5, a: 3, offset: 4 },
        Instruction::AddImmediate { d: 4, a: 8, immediate: 78 },
        Instruction::AddImmediate { d: 0, a: 8, immediate: 264 },
        Instruction::AddImmediate { d: 8, a: 8, immediate: 2 },
        Instruction::LoadHalfwordZeroIndexed { d: 4, a: 5, b: 4 },
        Instruction::StoreHalfwordIndexed { s: 4, a: 3, b: 0 },
        Instruction::BranchConditionalForward { options: 16, condition_bit: 0, target: 36 },
        Instruction::LoadWord { d: 4, a: 3, offset: 4 },
        Instruction::load_immediate(0, 3),
        Instruction::load_immediate(6, 0),
        Instruction::LoadWord { d: 4, a: 4, offset: 104 },
        Instruction::StoreWord { s: 4, a: 3, offset: 288 },
        Instruction::LoadWord { d: 4, a: 3, offset: 4 },
        Instruction::LoadHalfwordZero { d: 4, a: 4, offset: 108 },
        Instruction::StoreHalfword { s: 4, a: 3, offset: 292 },
        Instruction::MoveToCountRegister { s: 0 },
        Instruction::LoadWord { d: 5, a: 3, offset: 4 },
        Instruction::AddImmediate { d: 4, a: 6, immediate: 98 },
        Instruction::AddImmediate { d: 0, a: 6, immediate: 184 },
        Instruction::AddImmediate { d: 6, a: 6, immediate: 1 },
        Instruction::LoadByteZeroIndexed { d: 4, a: 5, b: 4 },
        Instruction::StoreByteIndexed { s: 4, a: 3, b: 0 },
        Instruction::BranchConditionalForward { options: 16, condition_bit: 0, target: 52 },
        Instruction::load_immediate(0, 4),
        Instruction::load_immediate(4, 0),
        Instruction::load_immediate(5, 0),
        Instruction::MoveToCountRegister { s: 0 },
        Instruction::AddImmediate { d: 0, a: 4, immediate: 56 },
        Instruction::AddImmediate { d: 4, a: 4, immediate: 4 },
        Instruction::StoreWordIndexed { s: 5, a: 3, b: 0 },
        Instruction::BranchConditionalForward { options: 16, condition_bit: 0, target: 63 },
        Instruction::load_immediate(0, 0),
        Instruction::StoreByte { s: 0, a: 3, offset: 2 },
        Instruction::LoadHalfwordZero { d: 4, a: 3, offset: 294 },
        Instruction::AddImmediate { d: 0, a: 4, immediate: 1 },
        Instruction::StoreHalfword { s: 0, a: 3, offset: 294 },
        Instruction::LoadHalfwordZero { d: 0, a: 3, offset: 294 },
        Instruction::CompareWordImmediate { a: 0, immediate: 0 },
        Instruction::BranchConditionalToLinkRegister { options: 4, condition_bit: 2 },
        Instruction::load_immediate(0, 1),
        Instruction::StoreHalfword { s: 0, a: 3, offset: 294 },
        Instruction::BranchToLinkRegister,
    ]);
}
